name: build-test

on: push

jobs:
  linux-build:
    name: Linux Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: linux-build
        run: |
          cd KarstNSim
          mkdir build
          cd build
          cmake ..
          make

  windows-build:
    name: Windows Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: windows-build
        shell: bash
        run: |
          cd KarstNSim
          mkdir build
          cd build
          cmake ..
          cmake --build .
          
